FROM linuxserver/letsencrypt
# Enable autoindex
RUN echo "autoindex on;" >  /etc/nginx/conf.d/autoindex.conf
# Rewrite /meetings
RUN sed -i '/try_files/c try_files $uri $uri/ /meetings/$request_uri =404;' /defaults/default
