FROM nginx:stable
ENV MEETINGS_LOCATION="/meetings"
COPY ["default.conf.template", "/etc/nginx/conf.d"]
CMD /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"