version: "3.7"

services:
  meetbot:
    build:
      context: ./
      dockerfile: Dockerfile-meetbot
    volumes:
      - data:/data
      - meetings:/data/meetings
    environment:
      SUPYBOT_FREENODE_PASSWORD: "somepasswordhere"
      SUPYBOT_FREENODE_CHANNELS: "#abaranov-test"
    networks:
      - meetbot
  letsencrypt:
    build:
      context: ./
      dockerfile: Dockerfile-letsencrypt
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - meetings:/config/www/meetings
    restart:
      always
    depends_on:
      - meetbot
    environment:
      PUID: 101
      PGID: 101
      URL: example.com
    
volumes:
  data: {}
  meetings: {}

networks:
  meetbot: 
