version: "3.7"

services:
  meetbot:
    build:
      context: ./
      dockerfile: Dockerfile-meetbot
    volumes:
      - data:/data
      - meetings:/data/meetings
    environment:
      SUPYBOT_NICK: "collabottest"
      SUPYBOT_FREENODE_PASSWORD: "s0mep@ssw0rd!test"
      SUPYBOT_FREENODE_CHANNELS: "#abaranov-test"
      SUPYBOT_LIBERA_PASSWORD: "s0mep@ssw0rd!test"
      SUPYBOT_LIBERA_CHANNELS: "#abaranov-test"
    networks:
      - meetbot
  web:
    build:
      context: ./
      dockerfile: Dockerfile-web
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - meetings:/config/www/meetings
    restart:
      always
    depends_on:
      - meetbot
    environment:
  #     MEETINGS_LOCATION: "/meetings"
    
volumes:
  data: {}
  meetings: {}

networks:
  meetbot: 
