version: "3.7"

services:
  meetbot:
    build:
      context: ./
      dockerfile: Dockerfile-meetbot
    volumes:
      - data:/data
      - meetings:/data/meetings
    environment:
      SUPYBOT_FREENODE_PASSWORD: JuWriagtolyitsubugtefWaw
      SUPYBOT_FREENODE_CHANNELS: "#abaranov-test"
    networks:
      - meetbot
  web:
    build:
      context: ./
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"
    environment:
      MEETINGS_LOCATION: /
    volumes:
      - meetings:/usr/share/nginx/html/
      - data:/data
    
volumes:
  data: {}
  meetings: {}

networks:
  meetbot: 
